import { expect, test } from '@playwright/test';

test('tracker shares habit progress with To do and shows daily details', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T10:00:00+07:00') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Go to Tracker' }).click();
  await expect(page.getByRole('heading', { name: 'Habit Tracker' })).toBeVisible();
  await expect(page.getByTestId('navigation-bottom')).toBeVisible();
  await page.getByRole('button', { name: 'Load sample data' }).click();
  await expect(page.locator('[data-testid^="tracker-habit-"]')).toHaveCount(3);
  await expect(page.getByText('No data yet')).toHaveCount(0);
  await page.getByTestId('tracker-cell-demo-water-2026-10-02').click();
  await expect(page.getByTestId('tracker-detail')).toContainText('4 / 8 cups');
  await expect(page.getByTestId('tracker-detail')).toContainText('50%');
  await expect(page.getByTestId('tracker-detail')).toContainText('In progress');
  await page.getByRole('button', { name: 'Close details' }).click();
  await page.getByRole('button', { name: 'Go to To do' }).click();
  await expect(page.getByText('4 / 8 cups', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Increase Drink water' }).click();
  await page.getByRole('button', { name: 'Go to Tracker' }).click();
  await page.getByTestId('tracker-cell-demo-water-2026-10-02').click();
  await expect(page.getByTestId('tracker-detail')).toContainText('5 / 8 cups');
  await expect(page.getByTestId('tracker-detail')).toContainText('63%');
  await page.getByRole('button', { name: 'Close details' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Go to Tracker' }).click();
  await page.getByTestId('tracker-cell-demo-water-2026-10-02').click();
  await expect(page.getByTestId('tracker-detail')).toContainText('5 / 8 cups');
});

test('week, month and year controls navigate and the year heatmap fits on phone', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T10:00:00+07:00') });
  await page.setViewportSize({ width: 320, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Go to Tracker' }).click();
  await page.getByRole('button', { name: 'Load sample data' }).click();
  await expect(page.getByTestId('tracker-cell-demo-water-2026-10-02')).toBeVisible();
  await page.getByRole('button', { name: 'Previous period' }).click();
  await expect(page.getByTestId('tracker-cell-demo-water-2026-09-25')).toBeVisible();
  await page.getByRole('button', { name: 'Current period' }).click();
  await expect(page.getByTestId('tracker-cell-demo-water-2026-10-02')).toBeVisible();
  await page.getByRole('tab', { name: 'Month' }).click();
  await expect(page.getByText('October 2026')).toBeVisible();
  await page.getByRole('button', { name: 'Previous period' }).click();
  await expect(page.getByText('September 2026')).toBeVisible();
  await page.getByRole('tab', { name: 'Year' }).click();
  await expect(page.getByText('Year 2026')).toBeVisible();
  const yearGrid = page.getByTestId('tracker-year-grid-demo-water');
  await expect(yearGrid).toBeVisible();
  const cardBounds = await page.getByTestId('tracker-habit-demo-water').boundingBox();
  const gridBounds = await yearGrid.boundingBox();
  const heatmapBounds = await yearGrid.getByRole('button', { name: /View year details/ }).boundingBox();
  expect(cardBounds && gridBounds).toBeTruthy();
  expect(heatmapBounds && heatmapBounds.width > 180).toBeTruthy();
  expect(gridBounds!.x + gridBounds!.width).toBeLessThanOrEqual(cardBounds!.x + cardBounds!.width - 8);
  expect(await page.getByTestId('tracker-year-scroll-demo-water').count()).toBe(0);
  await yearGrid.getByRole('button', { name: /View year details/ }).click();
  await expect(page.getByTestId('tracker-year-zoom')).toBeVisible();
  await page.getByRole('button', { name: 'October' }).click();
  await page.getByTestId('tracker-cell-demo-water-2026-10-02').click();
  await expect(page.getByTestId('tracker-detail')).toContainText('4 / 8 cups');
  await page.getByRole('button', { name: 'Close details' }).click();
  await page.getByRole('button', { name: 'Previous period' }).click();
  await expect(page.getByText('Year 2025')).toBeVisible();
  await page.getByRole('button', { name: 'Current period' }).click();
  await expect(page.getByText('Year 2026')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('existing habits are shown on desktop without inserting demo data', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-02T10:00:00+07:00') });
  await page.setViewportSize({ width: 1280, height: 850 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Add habit' }).click();
  await page.getByRole('textbox', { name: 'Habit name' }).fill('Read');
  await page.getByRole('button', { name: 'Create habit' }).click();
  await page.getByRole('button', { name: 'Go to Tracker' }).click();
  await expect(page.getByTestId('navigation-top')).toBeVisible();
  await expect(page.getByText('Read', { exact: true })).toBeVisible();
  await expect(page.getByText('No data yet')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Load sample data' })).toHaveCount(0);
  await page.getByRole('tab', { name: 'Year' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
